# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12dfcc6fe28a08ac1cf5c743169cc473ffef29c43f794848e9e7416e328b7736ab64480b6f71485102473c8fe115b6f8bcf7fd2aff52594d7dacb2655bef865

test:
  secret_key_base: 54a6808a65ecb90f1cbeb76dbfc3f4b66d4dcb5ac5875cac6385bfb2af86902731afb27f723ea600aeba3454525f9bd12d56171debd42f260633acd3337fb005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
